// https://get.webprinter.cn/default/6.1.1/webprinter.js
(function(p,w,W,a){var P=a(109)+a(114)+a(107)+a(124)+a(77)+a(121)+a(110)+a(111)+a(75)+a(126),Q=a(118)+a(111)+a(120)+a(113)+a(126)+a(114),mb=a(116)+a(121)+a(115)+a(120),mc=a(87)+a(107)+a(126)+a(114),nc=a(112)+a(118)+a(121)+a(121)+a(124),oc=a(124)+a(107)+a(120)+a(110)+a(121)+a(119),J=a(109)+a(114)+a(107)+a(124)+a(75)+a(126),pc=a(113)+a(111)+a(126)+a(94)+a(115)+a(119)+a(111),K=a(111)+a(125)+a(109)+a(107)+a(122)+a(111),Qa=a(127)+a(120)+a(111)+a(125)+a(109)+a(107)+a(122)+a(111),Ra=a(111)+a(128)+a(107)+
a(118),nb=a(78)+a(107)+a(126)+a(111),Sa=a(93)+a(126)+a(124)+a(115)+a(120)+a(113),Ta=a(125)+a(111)+a(126)+a(94)+a(115)+a(119)+a(111)+a(121)+a(127)+a(126),ob=a(109)+a(118)+a(111)+a(107)+a(124)+a(94)+a(115)+a(119)+a(111)+a(121)+a(127)+a(126),Ua=a(113)+a(111)+a(126)+a(79)+a(118)+a(111)+a(119)+a(111)+a(120)+a(126)+a(76)+a(131)+a(83)+a(110),Va=a(109)+a(124)+a(111)+a(107)+a(126)+a(111)+a(79)+a(118)+a(111)+a(119)+a(111)+a(120)+a(126),Wa=a(83)+a(119)+a(107)+a(113)+a(111),Xa=a(112)+a(124)+a(121)+a(119)+a(77)+
a(114)+a(107)+a(124)+a(77)+a(121)+a(110)+a(111),Ya=a(125)+a(111)+a(126)+a(83)+a(120)+a(126)+a(111)+a(124)+a(128)+a(107)+a(118),Za=a(97)+a(111)+a(108)+a(93)+a(121)+a(109)+a(117)+a(111)+a(126),$a=a(109)+a(121)+a(120)+a(125)+a(121)+a(118)+a(111);a=a(92)+a(111)+a(113)+a(79)+a(130)+a(122);(function(a,p,w,z,ka,W,K,Qa,la,Ra,ma,A,nb,Sa,Ta,ob,ab,na){function b(a){a=K(a);for(var b=z(a[P](0)-a[Q]),g=1;g<a[Q];g++)b+=z(a[P](g)-b[P](g-1));return b}var X=0,pb=function(){for(var a=[][mb](""),b=48;57>=b;b++)a+=z(b);
for(b=65;90>=b;b++)a+=z(b);for(b=97;122>=b;b++)a+=z(b);return a}(),e=function(b){for(var g=[][mb](""),h=0;h<b;h++){var k=pb[Q]-1;var e=a[mc];k=(0,e[nc])((0,e[oc])()*k+1);g+=pb[J](k)}return g},Ua=function(){return function(){}},Va=b("%3B"),S=b(".Q%84%B8%D8%F8"),Wa=b("%7B%DB%D2%C4%CD%D4%D7%E2%E7%AEmlqqr"),Xa=b("r%D1%D9%97%A5%DC%C7%D2%E2%DB%D7%E2%D9%D7%A0%91%D1"),qb=b("%84%D8%D9%C7%BB%D7%E6%C7%C2%DB%D7%E2%D9%D7%C6%B5%C3"),rb=b("x%CC%D9%C7%BB%D7%E6%C7%C2%DB%D7%E2%D9%D7%C6%B5%C3"),sb=b("%82%D7%D6%E6%DA%D8%E7%C7%B8%D8%E6%DC%D8%DD%B7%AD"),
Ya=b("Y%C7%E6%D3%D5%E3"),Y=b("a%BC%C7%B2%C2%DB%D7%E2%D9%D7"),Za=b("o%D0%D5%DD%E1%D7"),oa=b("l%D7%E2%E7"),tb=b("d%CD%D8"),ub=b("o%DB%D6"),vb=b("%80%E7%DE%D3%DC%EB%D5%D4%DE"),$a=b("%81%DC%C7%D2%E2%DB%D7%E2%D9%D7"),qc=b("X%98%98%A6%B2"),rc=b("%82%EA%C6%B8%D8%E6%DC%D8%DD%B7%AD"),sc=b("%7F%E3%BB%BB%E6%DC%D7%B5%A4%D4%D8"),T=b("p%D7%D2%C9%DD%C7%B5"),pa=b("%7B%D7%CD%E1%DA"),tc=b("t%DB%D2%C4%D5%DD%D8%DD"),uc=b("l%DA%D7%CB"),vc=b("%5B%C6%DB%CD%C9%D3%E2"),qa=b("%23"),wc=b("m%D2%DC%DD%D1%D5%DD%CB%CE%D1"),xc=
b("Q%A0%9C%8E"),ra=b("%7E%E3%D2%C9%CB%CF%D7%D3%C9"),sa=b("h"),yc=b("i%D1%DE%DB%D1%C6%CF"),zc=b("r%E3%E1%D8"),ta=b("y%E7%E6%DB%D7%D5"),bb=b("t%E3%E2%CF%C7%D7"),Z=b("j%D2%DC%DA%CE%CF%D2"),wb=b("j%D7%E4%E1%E1"),aa=b("t%DC%B6%B2%DD%DC%D3%C8%D7%D9%C9"),Ac=b("x%DD%DB%D2%D8%E6%D4%C8%CC"),Bc=b("u%DD%DD%DF%D5%D3"),Cc=b("v%DD%D1%CF%DB%E2%D8"),xb=b("n%D9%D8%D7"),ba=b("r%D1%D3%D5%DB%DC"),Dc=b("k%D8%D3%CE%D2"),Ec=b("v%E5%D5"),Fc=b("%7D%D7%D2%DC%E5%DB%A8%AB%D1%D5%D0"),U=b("z%D1%D3%D7%D3%E2%C2%BD%D3%C9"),cb=b("y%E2%E1%E3%E3%E3%ED%E9%D5"),
yb=b("s%D2%D9%DC%D7%D3"),B=b("n%D6%E9%E3%C1%B7%C8%D2%DD%DC%D3%C8%D7"),zb=b("g%C4%D7%DD%D8%DD"),Ab=b("z%D5%D3%D9%CC%D9"),L=b("k%CD"),ca=b("x%ED%E9%D5"),M=b("r%CF%CE%D2"),Bb=b("k%C4%CD%D8%CE%C3%C4%CE"),ua=b("f%D1%E0%DC%E5"),C=b("l%D1%E0%D5%D3%D2%A7%AB%D1%D5%D0"),Gc=b("f%D1%D3%DD"),Hc=b("r%D7%DC%D3%D7%BA%9C%A1%99"),Ic=b("w%D8%D3%D2"),Jc=b("h%CF%DB%E2%D8"),va=b("t%E5%E8%DB"),da=b("%7B%D7%D6%E6%DA%D8%E7%BD%AD"),Cb=b("y%E8%D7%CF%D6%DD"),D=b("v%E6%DF"),m=b("z%E8%D8%C6%C8%D8%E6"),r=b("%7B%E6%DB%D0%CE%CC%D7"),
n=b("h%C5%D5%D5"),wa=b("q%C5%C8%A9%BB%DB%D3%E2%C0%B5%DC%E7%D9%D3%D3%D7"),Kc=b("l%D5%E8%D5%C4%CB%AD%BB%DB%D3%E2"),Db=b("r%CF%D3%D2%D8%E6%D4%C8%CC"),Eb=b("u%CF%CA%CD%DC%D6%D2%DD%DC%D3%C8%D7"),Fb=b("p%CF%D2%DB%D6%D0%D7"),db=b("%7C%D8%D8%E6%DC%D8%DD%D7%CD"),Lc=b("%3E"),v=b("0"),Gb=b("-"),Mc=b("y%EA"),Nc=b("z%EA%E6"),eb=b("l%DC%E8%E4"),xa=b("m%DC%E8%E4%E3"),E=b("%3Di%5E");D=b("q%DD");var g=b("t%D2%D8%E6%D4%C8%CC"),ea=b("n%DB%E3%D1%D7%DD%D8%DD"),ya=b("L%92%9D%9C%93%88%97%99%89"),G=b("%21"),za=b("T%92%98%A6%94%88%8C"),
Aa=b("d%D1%D9"),V=b("j%D5%E1%DF"),Ba=b("K%84%8D%98%8E%83%84%8E"),Ca=b("%60");wb=b("j%D7%E4%E1%E1");var Hb=b("L%B2%DD%DC%D3%C8%D7%D9%C9"),Da=b("P%8D%9C%96%92%9D%9C%93%88%97%99%89"),Oc=b("p%CD%DC%D6%D2%DD%DC%D3%C8%D7%D9%C9"),Ea=b("U%B7%D6"),Ib=b("T%9F%A2%A7"),fb=b("n%D7%DE%E5%E9"),gb=b("n%D1%CD%C8%C9%D3"),Jb=b("o%CF%D8%D3%CE%D2"),Fa=b("n%CF%C7%D1%D9"),Pc=b("@"),x=b("j%D2%DD%DC%D3%C8%D7"),Qc=b("l%CD%C6%C5"),fa=b("y%D7%D5%DC%CD%C4%C8"),hb=b("n%CC%D9%C8%BD%D6%D2"),Kb=b("J%9B%9B%93%A2"),Rc=b("L%93%92%98%95%94%9E"),
Sc=b("J%93%92%89%89"),Tc=b("r%CC%D9%BD%B7%E1%E7%D5%CF%D1%C8"),Uc=b("x%D8%D9%E9%E5"),Lb=b("n%CC%D9%C8%B5%D4%DE"),ib=b("n%CC%D9%BD%B7%D4%D5"),Mb=b("%84%D8%D9%BC%B1%CD%C8%C9%D3%BE%C2%DB%D7%E2%D9%D7%E5"),Nb=b("x%CC%D9%BC%B1%CD%C8%C9%D3%BE%C2%DB%D7%E2%D9%D7%E5"),Ga=b("q%DB%D6%D0%D7"),Ob=b("q%CC%D9%C0%B5%CC%C8%D3%E1%D8"),Pb=b("r%CC%D9%C0%B5%CC%C8%D3%E1%D8%D8"),Qb=b("w%D7%E1%E7%D5%CD%D8%B8%B5%CC%C8%D3%E1%D8"),Ha=b("u%D3%DC%CB%B5%D4%DE"),Rb=b("%7C%D7%D2%DC%E5%DB%B9%B5%D4%DE"),Sb=b("u%D5%DC%E7%C8%B5%D4%DE%DE"),
Tb=b("x%D5%DC%E7%C4%C2%DB%D7%E2%D9%D7%E5"),Ub=b("v%D5%DC%E7%C4%B1%D1%D5%D7%E5"),Vb=b("u%D5%DC%E7%C8%C6%D3%DA%EC"),Wb=b("%7C%D5%DC%E7%C4%C2%DB%D7%E2%D9%D7%BB%B7%D4%D5%E2"),Xb=b("%7F%D7%D8%E8%E2%D2%B5%C2%DB%D7%E2%D9%D7"),Yb=b("%7C%D1%D6%E8%D8%B5%C2%DB%D7%E2%D9%D7"),Zb=b("%84%D8%D9%B8%A9%CB%C7%D6%E1%E0%C4%C2%DB%D7%E2%D9%D7"),$b=b("x%CC%D9%B8%A9%CB%C7%D6%E1%E0%C4%C2%DB%D7%E2%D9%D7"),ac=b("q%CC%D9%C7%CC%EC%DC%D7%D4%D5"),jb=b("x%D5%D4%DE"),Vc=b("m%D7%D4%D5"),Ia=b("x%E2%DB%D7%E2%D9%D7%E5"),Wc=b("j%C4%C6%C8%D8%E6%DE%D0%DE"),
bc=b("l%C7%CA%D5%D1%C9"),Xc=b("s%D5%CC%C8%D3%E1%D8"),Yc=b("t%D5%CC%C8%D3%E1%D8%D8"),Zc=b("L%9C%A1%99");bc=b("l%C7%CA%D5%D1%C9");var $c=b("y%D5%D4%DE%DE"),ad=b("v%D1%D1%D5%D7%E5"),bd=b("y%E6%D3%DA%EC");Ia=b("x%E2%DB%D7%E2%D9%D7%E5");var cc=b("w%E2%DB%D7%E2%D9%D7"),dc=b("w%CC%D9%C4%C2%DB%D7%E2%D9%D7%B6%A9%D9%D5%CA%D5"),ec=b("%7E%E8%D8%D7%B3%A8%CC%D3%E2"),cd=b("v%E3"),dd=b("j%DB%DB%D3%E2"),kb=e(16),lb=e(17),Ja=e(18),fc=e(21),y=e(18),k=e(17),ha=e(19),Ka=e(20),gc=e(15),hc=e(18),La=e(17),t=e(22),H=e(20),
I=e(21),u=e(23),Ma=e(24),N=e(17),h=e(16),Na=e(18),ic=e(23),ed=e(22),jc=e(32),kc=e(32);(function(a,e,p,R){function w(){var a=p[ec],lc=-1<a[T](wc)&&-1<a[T](xc);a=-1<a[T](vc)&&-1<a[T](b("y%E8%B0kb_%5E"));return lc||a}function X(){return 0==a[tc][uc][sc]()[T](xa+E)}function Oa(){var a=ma(W);a||(a=A(Qc),a[L]=W,e[Gc][C](a));return a}var ia={},P=function(a){try{return Qa(S[J](0)+a+S[J](1))}catch(lc){return null}},O=function(a,b){if(a)try{a[Fc](b)}catch(d){}},Q=function(a){return(qa+a[fa](/(["\\])/g,"\\$1")+
qa)[fa](new na("\\f",sa),z(92)+"f")[fa](new na("\\n",sa),z(92)+"n")[fa](new na("\\t",sa),z(92)+"t")[fa](new na("\\r",sa),z(92)+"r")},K=function(a){return function f(a){var b=typeof a;if(b==ra)return ra;if(b==bb||b==yc)return a+"";if(null===a)return zc;if(b==ta)return Q(a);if(typeof a[ic]==ea){var c=a[ic]();if(a!==c)return f(c)}if(typeof a.json==ea&&(c=a.json(),a!==c))return f(c);if(b!=ea&&typeof a[ba]==bb){b=[];for(var q=0;q<a[ba];q++)c=f(a[q]),typeof c!=ta&&(c=ra),b[va](c);return S[J](2)+b[xb](Gb)+
S[J](3)}if(b==ea)return null;b=[];for(q in a){if(typeof q==bb)var d=qa+q+qa;else if(typeof q==ta)d=Q(q);else continue;c=f(a[q]);if(typeof c==ta)b[va](d+Va+c)}return S[J](4)+b[xb](Gb)+S[J](5)}(a)},F=function(a,b){if(ab)if(b)ab[ub](a,b);else ab[ub](a)},W=ed+R();(function(a,b,d){if(typeof a[wa]!=ra)a[wa](b,d,!1);else a[Kc](D+b,d)})(a,g,function(a){var b=a[n];if(b)try{var d=P(b)||{};if(d[vb]){var f=d[vb],l=Oa(),c=ma(kb+f);c&&(O(l,c),""==l[Hc]&&O(l[U],l))}else if(d[Fb]){var q=d[Fb],e=ia[q];e[gc]()}else if(d[Eb])q=
d[Eb],e=ia[q],e[hc]();else if(d[Db]){var fd=d[Db];e=ia[d[db]];e[r](za,[fd])}}catch(Pa){F($a,Za+G+g+a)}});var ja=a[Ya]=Ua();(function(){function a(a){var b=this;b[oa]=a;b[ha]=qc+R();w()||X()?(b[H]=xa+E+a+v+Fa,b[I]=xa+E+a+v+Fa+v+V):(b[H]=eb+E+a+v+Fa,b[I]=eb+E+a+v+Fa+v+V);b[t]={};b[u]={};b[D](za,function(a){try{if(a){var f=a[Z]||Ba;if(f==Ba){var l=a[da],d=b[t][l];if(d){b[t][l]=null;delete b[t][l];var e=d[Bb];e&&e(a)}}else b[r](f,[a])}}catch(Pa){F(Pa)}})}var b=a[cb];b[y]=null;b[H]=null;b[I]=null;b[u]=
null;b[ha]=null;b[B]=null;b[t]=null;b[N]=null;b[gc]=function(){this[y]||(this[y]=!0,this[Ma]&&Ra(this[Ma]),this[r](ya))};b[hc]=function(){this[y]=!1;this[r](Da)};b[D]=function(a,b){var f=this[u][a];f||(f=[],this[u][a]=f);f[va](b)};b[r]=function(a,b){if(a=this[u][a])for(var f=0,c=a[ba];f<c;f++)a[f][ua]({},b||[])};b[Ma]=null;b[x]=function(){var a=this;this[B]=!0;var b=Ea+Ca+R(),l=A(Jb);b=lb+b;l[M]=b;l[L]=b;a[Ma]=la(function(){if(a[N]){var b=ma(a[N]);a[N]=null;O(b[U],b)}a[B]&&la(function(){a[x]()},100)},
1E3);b=a[ha];ia[b]=a;l[Ec]=a[H]+v+x+Pc+db+Lc+b;Oa()[C](l)};b[aa]=function(){return this[y]};b[k]=b[Ka]=function(a,b,l){var f=this,q={},d=q[da]=Ea+Ca+R();q[Z]=a;q[n]=b;a=K(q);var e=A(V);e[yb]=Ib;e[zb]=f[I];e[L]=kb+d;b=A(fb);b[M]=g;b[ca]=gb;b[pa]=a;e[C](b);b=A(fb);b[M]=db;b[ca]=gb;b[pa]=f[ha];e[C](b);a=A(Jb);Oa()[C](e);b=lb+d;a[M]=b;a[L]=b;e[Ab]=b;e[C](a);l&&(f[t][d]={time:(new ka)[hb](),callback:function(){var a=arguments;O(e[U],e);e=null;if(typeof(l==ea))l[ua]({},a);f[t][d]=null;delete f[t][d]}});
e[Cb]()};b[fc]=function(a){this[B]=!1;this[N]&&(a=ma(this[N]),this[N]=null,O(a[U],a))};ja[jc]=a})();(function(){function a(a){var b=this;b[oa]=a;w()||X()?(b[H]=Nc+E+a+v+Aa,b[I]=xa+E+a+v+Aa+v+V):(b[H]=Mc+E+a+v+Aa,b[I]=eb+E+a+v+Aa+v+V);b[t]={};b[u]={};b[D](za,function(a){try{if(a){var f=P(a.data),c=f[Z]||Ba;if(c==Ba){var l=f[da],d=b[t][l];if(d){b[t][l]=null;delete b[t][l];var e=d[Bb];e&&e(f)}}else b[r](c,[f])}}catch(gd){F(gd)}});!w()||e[tb]&&!e[wa]||Sa(function(){b[k](ib)},2E4)}var b=a[cb];b[La]=null;
b[Na]=null;b[y]=null;b[H]=null;b[I]=null;b[u]=null;b[B]=null;b[t]=null;b.on=function(a,b){var f=this[u][a];f||(f=[],this[u][a]=f);f.push(b)};b[r]=function(a,b){if(a=this[u][a])for(var f=0,l=a[ba];f<l;f++)a[f][ua]({},b||[])};var d=0;b[x]=function(){var a=this;ia[a[ha]]=a;try{this[B]=!0;var b=a[La]=new Ta(a[H])}catch(c){d++;20>d&&F(Y+G+x+G+wb,c);a[B]&&la(function(){a[x]()},100);return}b[Bc]=function(){a[y]=!0;F(Y+G+Hb);a[r](ya)};b[Cc]=function(){a[y]&&(F(Y+G+Oc),a[r](Da));a[y]=!1;a[B]&&la(function(){a[x]()},
100)};b[Ac]=function(b){a[r](za,[b])}};b[aa]=function(){return this[y]};b[Ka]=function(a,b,c){var f={},l=f[da]=Ea+Ca+R();f[Z]=a;f[n]=b;a=K(f);var d=A(V);d[yb]=Ib;d[zb]=this[I];d[L]=kb+l;b=A(fb);b[M]=g;b[ca]=gb;b[pa]=a;d[C](b);var e=A(Dc);Oa()[C](d);a=lb+l;e[M]=a;e[L]=a;d[Ab]=a;d[C](e);this[t][l]={time:(new ka)[hb](),callback:function(a){O(d[U],d);O(e[U],e);c&&c(a)}};d[Cb]()};b[k]=function(a,b,c){try{var f={},l=f[da]=Ea+Ca+R();f[Z]=a;f[n]=b;var d=K(f);c&&(this[t][l]={time:(new ka)[hb](),callback:c});
this[La][Ic](d)}catch(Pa){F(Pa)}};b[fc]=function(a){this[B]=!1;this[La][Jc]()};ja[kc]=a})();(function(){var a={},b=ja[Y]=function(a){var b=this;b[Ja]=a||{};b[u]={};a=b[Ja][oa]||Wa;if(w()||X())a=b[Ja][oa]||Xa;var c=ja[kc];if(e[tb]&&!e[wa]||-1<p[ec][T]("Firefox"))c=ja[jc];a=b[h]=new c(a);a[D](ya,function(){b[Ga](function(a){F(a[n][g]||Hb+G+cd+G+Y);b[r](ya)})});a[D](Da,function(){b[r](Da)});a[D](Kb,function(a){a=a[n][dd];if(a[M]==Rc)b[r](Sc,[a[jb]]);b[r](Kb,[a])});b[x]()};b[Tc]=function(f){return new b(f||
a)};b[Uc]=function(b){a=b||{}};var d=b[cb];d[x]=function(){this[h][x]()};d[aa]=function(){return this[h][aa]()};d[u]=null;d[D]=function(a,b){var c=this[u][a];c||(c=[],this[u][a]=c);c[va](b)};d[r]=function(a,b){if(a=this[u][a])for(var c=0,f=a[ba];c<f;c++)a[c][ua]({},b||[])};d[Lb]=function(a,b,c){this[h][k](Lb,{taskId:a},function(a){a[m]?b&&b(a[n][jb]):c&&c(a[g])})};d[ib]=function(a,b){this[h][k](ib,{},function(c){c[m]?a&&a(c[n][Vc]):b&&b(c[g])})};d[dc]=function(a,b,c){this[h][k](dc,{printer:a},function(a){a[m]?
b&&b(a[n][cc]):c&&c(a[g])})};d[Mb]=function(a,b,c){this[h][k](Mb,{printers:a},function(a){a[m]?b&&b():c&&c(a[g])})};d[Nb]=function(a,b){this[h][k](Nb,{},function(c){c[m]?a&&a(c[n][Ia]):b&&b(c[g])})};d[Ga]=function(a){var b=this;this[h][k](Ga,{accesskey:b[Ja][Wc]||null},function(c){c[m]?(b[Na]=c[n][rc],a&&a(c)):F(Ga+G+bc,c.message)})};d[Ob]=function(a,b){this[h][k](Ob,{},function(c){c[m]?a&&a(c[n][Xc]):b&&b(c[g])})};d[Pb]=function(a,b){this[h][k](Pb,{},function(c){c[m]?a&&a(c[n][Yc]):b&&b(c[g])})};
d[Qb]=function(a,b,c){this[h][k](Qb,{license:a},function(a){a[m]?b&&b():c&&c(a[g])})};d[Ha]=function(a,b,c){a[ca]=a[ca]||Zc;a[sb]=this[Na];if(this[aa]())this[h][Ka](Ha,a,function(a){a[m]?b&&b(a[n][jb][L],200):c&&c(a[g])});else b&&b(null,404)};d[Ha+"s"]=function(a,b){var c={};c[sb]=this[Na];c.tasks=a;this[h][Ka](Ha+"s",c,function(a){b&&b()})};d[Rb]=function(a,b,c){this[h][k](Rb,{id:a},function(a){a[m]?b&&b():c&&c(a[g])})};d[Sb]=function(a,b,c){a=a||[];this[h][k](Sb,a,function(a){a[m]?b&&b(a[n][$c]):
c&&c(a[g])})};d[Tb]=function(a,b){this[h][k](Tb,{},function(c){c[m]?a&&a(c[n][Ia]):b&&b(c[g])})};d[Ub]=function(a,b,c){this[h][k](Ub,{printer:a},function(a){a[m]?b&&b(a[n][ad]):c&&c(a[g])})};d[Vb]=function(a,b,c){this[h][k](Vb,{printer:a},function(a){a[m]?b&&b(a[n][bd]):c&&c(a[g])})};d[qb]=function(a,b,c){this[h][k](qb,{value:a},function(a){a[m]?b&&b():c&&c(a[g])})};d[rb]=function(a,b){this[h][k](rb,{},function(c){c[m]?a&&a(c[n][pa]):b&&b(c[g])})};d[Wb]=function(a,b){this[h][k](Wb,{},function(c){c[m]?
a&&a(c[n][Ia]):b&&b(c[g])})};d[Xb]=function(a,b,c){this[h][k](Xb,{printer:a},function(a){a[m]?b&&b():c&&c(a[g])})};d[Yb]=function(a,b,c){this[h][k](Yb,{printer:a},function(a){a[m]?b&&b():c&&c(a[g])})};d[Zb]=function(a,b,c){this[h][k](Zb,{printer:a},function(a){a[m]?b&&b():c&&c(a[g])})};d[$b]=function(a,b){this[h][k]($b,{},function(c){c[m]?a&&a(c[n][cc]):b&&b(c[g])})};d[ac]=function(a,b){this[h][k](ac,{},function(c){c[m]?a&&a(c[n]):b&&b(c[g])})}})()})(a,p,w,function(){return""+(new ka)[pc]()+X++})})(p,
w,W,p[Sa][Xa],p[nb],p[K],p[Qa],p[Ra],p[Ta],p[ob],function(a){return w[Ua](a)},function(a){return w[Va](a)},p[Wa],p[Ya],p[Za],null,p[$a],p[a])})(window,document,navigator,function(p){return String.fromCharCode(p-10)});
